### ISSUE TITLE
A small bug which does not harm too much but can be inconvenient from time to time

### ISSUE THREAD

**Issue by Joursach** [LuziferSenpai/Senpais-Trains#2]
When I click anywhere in the vecinity of the "S" (Senpai) symbol in the top left corner (not directly on it) a bug pops up: 
"Error while running event
Senpais_Trains::on_gui_click (ID 1)
_ _Senpais_Trains_ _/control.lua:88: attempt to index local 'pa'(a nil value)"

I hope that this information is helpful in your endeavor to make your awesome mod even more awesome.

Thank you for your work!

**Comment by LuziferSenpai** [comment]
Fixed in Version 1.1.3
