### ISSUE TITLE
Error with trains on manual mode

### ISSUE THREAD

**Issue by azak1r** [LuziferSenpai/Senpais-Trains#3]
Been rebuilding my base with trains all stationary in manual mode when all of a sudden this popped up. Thought it was something i did but after another attempt it happened again.
all double headed trains

![image](https://user-images.githubusercontent.com/903192/42469265-7d4694fa-83b7-11e8-9973-b619fa8a7749.png)

running your latest version of the mod.

**Comment by LuziferSenpai** [comment]
I hope its fixed this Version.

**Comment by azak1r** [comment]
pulling the update. will provide feedback if the error is gone or not

**Comment by azak1r** [comment]
4 hour session with same setup on trains no issues what so ever. thanks for the fix
