### ISSUE TITLE
Error loading savegame with version 1.1.5

### ISSUE THREAD

**Issue by jasperanja** [LuziferSenpai/Senpais-Trains#4]
Hello,

I'm running the latest stable build of factorio 0.16.51. I've have the latest version of your great mod installed : 1.1.5

After I load a save game I get the following error :

Notive
Error while running event
Senpais_Trains::on_train_changed_strate (ID 23)
__Senpais_Trains__/control.lua:284:attempt to index local 's' (a nil value)

In the past I had no problems running this game. But today I updated this mod to its latest version. I this before today I used a 2 month old version. After that I get the error message stated above after about 10 seconds into the game.

I deleted the mod, restarted the game and reinstalled the mod. After that the issue is still there. I don't have this problem if I start a new game.

If you need more information regarding this problem, please let me know.

Regards, Jasper

[factorio-current.log](https://github.com/LuziferSenpai/Senpais-Trains/files/2189245/factorio-current.log)

**Comment by LuziferSenpai** [comment]
I will look into it, when I get home. So tomorrow/Monday.

**Comment by jasperanja** [comment]
Thank you for the quick repley ! Take your time and if you need some more information or files please let me know.

**Comment by LuziferSenpai** [comment]
Hopefully fixed in Version 1.1.6
