### ISSUE TITLE
Multiple errors while creating line

### ISSUE THREAD

**Issue by RadiantShift** [LuziferSenpai/Senpais-Trains#5]
Mod version: 0.1.22
Game version: 1.1.6
Other mods: none

Place rails. Place train stop and train itself.
Press S-button on the top of the screen, press line management button, select train, press pink plus button, enter any name and select any icon, press add line.
It results to
> Error while running event Senpais_Trains::on_gui_click (ID 1)
>__Senpais_Trains__/functions.lua:722: attempt to index local 's' (a nil value)

Place rails. Place train stop and train itself.
Press S-button on the top of the screen, press line management button, select train, add train stop to trains schedule, press pink plus button, enter any name and select any icon, press add line (now we have some panels floating, must press S-button again to fix it),  Then go again to line management, select mewly created line in dropdown menu, and try to set train stop icon in window. It results to 
>Senpais_Trains::on_gui_elem_changed (ID 67)
>__Senpais_Trains__/control.lua:248: attempt to concatenate field 'name' (a nil value)

**Comment by LuziferSenpai** [comment]
I work on it.

**Comment by LuziferSenpai** [comment]
Should be fixed in Version 1.2.0. Pls give me Feedback.

**Comment by RadiantShift** [comment]
Now line is successfully created, but i getting

> Error while running event Senpais_Trains::on_gui_click (ID 1)
> Gui element with name SenpaisTrainsFrame27 already present in the parent element.
> stack traceback:
> 	__Senpais_Trains__/functions.lua:670: in function 'AddFrame'
> 	__Senpais_Trains__/functions.lua:419: in function 'SmarterTrainsMain'
> 	__Senpais_Trains__/control.lua:158: in function <__Senpais_Trains__/control.lua:73>

while trying to remove it immediately after creation.

**Comment by LuziferSenpai** [comment]
Yea, i will fix it. Its a Problem with my new Code.

**Comment by LuziferSenpai** [comment]
Should be fixed in Version 1.2.1. Pls give me Feedback.

**Comment by RadiantShift** [comment]
Yes, it fixed now. Thanks!
