### ISSUE TITLE
Error while loading save

### ISSUE THREAD

**Issue by Patti2507** [LuziferSenpai/Senpais-Trains#6]
When I load into my game I get the error
,,Error while running event Senpais_Trains::on_tick
(ID 0)
_ _Senpais_Trains_ _/control.ua:387: attempt to
index field '?' (a nil value) "
I really dont want to uninstall your mod since its very good and I dont  want to break my whole base xD

**Comment by Whiterhin** [comment]
I am having the same issue. 
![factiorio](https://user-images.githubusercontent.com/41874808/43369244-9f4bd818-9338-11e8-85ff-33aae1c9890f.JPG)

**Comment by LuziferSenpai** [comment]
I think you need to reinstall my MOD, remove my Modification, start the Savegame, save it and than install my Modification again. There cant be a Bug in my Code in that Line, but I think its because of many Changes of the tick Event.

**Comment by Patti2507** [comment]
Well that sucks, since that was what I wanted to avoid, cause I didnt want to lose all of my trains. Well thanks for your help anyway 👍

**Comment by LuziferSenpai** [comment]
Well it could be if you have an older Version than the current.

**Comment by Whiterhin** [comment]
I always keep my mods up to date and have tried reinstalling your mod, but I never saved the map with the mod uninstalled.  I was trying to prevent the havoc it is going to cause for my large base, but I will try your suggestion anyways. 

By the way, I truly enjoy the electric trains and Dora. Thanks for the great mod.

**Comment by LuziferSenpai** [comment]
Thanks. Yea I'm working on more Stuff :D
