### ISSUE TITLE
갑자기 잘되다가 안돼요

### ISSUE THREAD

**Issue by ghost** [LuziferSenpai/Senpais-Trains#7]
![default](https://user-images.githubusercontent.com/42403714/44138971-a2df87ba-a0b0-11e8-9c0f-2dd4c421915c.PNG)
이런오류가뜨면서 새로운맵으로 시작하면돼는데 원래적용했던 맵에 들어가면 저사진처럼돼요

**Comment by LuziferSenpai** [comment]
You should update the Modification to the newest Version, because in these Lines CANT be a Bug like this in the newer Versions.

**Comment by ghost** [comment]
이미 최신버전이였으며 다시 설치해도안됍니다 모드를 업데이트 시켜주세요

2018년 8월 17일 (금) 오전 6:18, Luzifer Senpai <notifications@github.com>님이 작성:
