### ISSUE TITLE
Uncoupling

### ISSUE THREAD

**Issue by Tokito99** [LuziferSenpai/Senpais-Trains#8]
Hi Senpai,

in this Modpack the Uncoupling still doesnt work. The Coupling works fine but the doubleheaded trains dont react to the Uncoupling Signal attached to the Station. The Original Signal from the "Automatic Coupler 0.16" Mod works fine but with the immediate depart.

**Comment by LuziferSenpai** [comment]
Thanks for the report, I'm working on fixing it.

**Comment by LuziferSenpai** [comment]
Fixed, in a new MOD. This MOD will no longer get supported.
