### ISSUE TITLE
Error loading save after update Senpais trains to v1.2.1

### ISSUE THREAD

**Issue by Yokoyhama** [LuziferSenpai/Senpais-Trains#9]
After updating Senpais trains to v1.2.1 I get an error after loading the game:

>     Error while running event Senpais_Trains::on_tick (ID 0)
>     __Senpais_Trains__/control.lua:387: attempt to index field '?' (a nil value)

The game chat gives a messages

>     FARL version changed form 2.1.1 to 2.1.2

After clicking "OK" the game goes back to the main menu.

Setting Senpai trains back to v1.0.7 (witch I was using before) fixes the problem.
I'm using factorio [0.16.51].

**Comment by LuziferSenpai** [comment]
This Modification is no longer supported. It will get splitt.
